# Generated by Django 3.1.4 on 2020-12-22 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id_department', models.AutoField(primary_key=True, serialize=False)),
                ('department_name', models.CharField(max_length=100, null=True)),
                ('parent_dep', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Employer.departments')),
            ],
        ),
        migrations.CreateModel(
            name='OfficalHolidays',
            fields=[
                ('id_holidays', models.AutoField(primary_key=True, serialize=False)),
                ('holiday_name', models.CharField(max_length=200, null=True)),
                ('active_flag', models.BooleanField(default=True)),
                ('last_active', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id_role', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=200, null=True)),
                ('min_salary', models.FloatField(null=True)),
                ('max_allowance_no', models.IntegerField(null=True)),
                ('lifespan', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id_user', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100, null=True)),
                ('salary', models.FloatField(null=True)),
                ('email', models.EmailField(max_length=100)),
                ('phone_no', models.CharField(max_length=200, null=True)),
                ('hire_date', models.DateField(auto_now_add=True)),
                ('department_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Employer.departments')),
            ],
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(auto_now_add=True)),
                ('role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Employer.role')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Employer.users')),
            ],
        ),
        migrations.AddField(
            model_name='role',
            name='users',
            field=models.ManyToManyField(through='Employer.UserRole', to='Employer.Users'),
        ),
        migrations.CreateModel(
            name='AllowanceRequest',
            fields=[
                ('id_request', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('start_hour', models.TimeField(default='00:00:00')),
                ('end_hour', models.TimeField(default='23:59:59')),
                ('approval_flag', models.BooleanField(default=False)),
                ('approver_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aprovuesi', to='Employer.users')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kerkuesi', to='Employer.users')),
            ],
        ),
    ]
