# Generated by Django 3.1.4 on 2020-12-23 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employer', '0003_auto_20201222_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='allowancerequest',
            name='checked',
            field=models.BooleanField(default=False),
        ),
    ]
