# Generated by Django 3.1.4 on 2020-12-24 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employer', '0004_allowancerequest_checked'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='password',
            field=models.CharField(default='KokaNeStamboll', max_length=500),
        ),
    ]
